### ISSUE TITLE
Improved transient caching and cache busting for calendars

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#2]
EO caches calendar output in a transient. This transient is pretty monolithic, and is definitely not group-sensitive, so it needs to be busted every time we display the calendar.

Here's @christianwach's fix: https://github.com/cuny-academic-commons/bp-event-organiser/blob/master/bp-event-organiser-eo.php#L491 This works, but we should look for a better fix.
1. Petition for a filter (in EO) on the key used for the transient. We could filter it and make it group-specific.
2. Petition for a filter or some other param (again, in EO) that would allow us to bypass the calendar cache. We could then write our own caching for this - I understand why it was written to use transients, but for CAC (where we know we have a proper persistent cache) we could do something better.
3. Some other magical thing.

@christianwach Assigning to you as you've done much of the prior work. Let me know what you think is the best way forward.

**Comment by christianwach** [comment]
I'll look into the options, @boonebgorges - thanks for setting them out

**Comment by christianwach** [comment]
So, I've had an interesting conversation with Steven [here](https://github.com/stephenharris/Event-Organiser/pull/248), the outcome of which suggests that we could use the `pre_set_transient_{$transient}` and `pre_transient_{$transient}` filters to override whatever transients EO might try and save. He also suggested an alternative filter we might consider - namely on the transient data array's key.

Also of relevance is our conversation from late 2013 on the same issue applied to shortcodes https://github.com/stephenharris/Event-Organiser/issues/127

I'll try a few variants out, but would be interested in others' opinions on what needs saving (EO currently saves the query) and therefore which route would be the most efficient (or elegant) for our purposes. FWIW, at the moment, I'm favouring the `pre_transient_{$transient}` route as I think it gives us the greatest flexibility.

**Comment by boonebgorges** [comment]
Thanks for getting the conversation started, @christianwach.

Looking at the transient code in EO more closely, I'm not sure there's a very elegant way to hook in. EO is generating the array key for the query by using the `$query` variable, which is built from the hardcoded `$presets` and a whitelist of `$request` params passed as part of `$_GET`. So I guess we'd have to grab the value of `$_GET['bp_group_id']` and somehow append it to the `md5()`-generated string in order to make a unique array key? I guess I'm not sure why this is all necessary in the first place since the group-filtering happens post-query anyway (`intercept_calendar()`).

Christian, if you can figure out a working version of what you've got in mind, it'd be great to take a look at it.

**Comment by stephenharris** [comment]
Just thought I'd stop by to say I'm open to suggestions regarding transient handling of the calendars so that it can fix this.

As you're probably aware EO uses a known transient key to store an array of cached data indexed be cache index generated by `md5()` of the `$query`. The aim is to be able to clear the entire cache (poor man's rubbish collection). At the moment, though, generation of the cache index it's pretty locked down. 

There are three ways of resolving this as far as I can see:
1. Disable the cache - as @christianwach mentioned (with the obvious downsides)
2. EO adds a filter of the cache index to allow you to change it as required to account (for example) for `$_GET['bp_group_id']`
3. EO uses the entire contents of `$_REQUEST` to generate the key

(1) isn't a great option, and (2) seems to add more work than is necessary. (3) seems the most cleanest and the most reliable solution, however my concern with it is that the cache array could explode in size. I'm open to suggestions, but caching and calendars seem not to mix well.

**Comment by boonebgorges** [comment]
Thanks for stopping by and sharing your thoughts, @stephenharris.

I would personally recommend against (3). People can send all sorts of junk in `$_REQUEST`, and some of it will not be relevant to query caches. (What if we added a nonce to these requests for some reason? It'd make the cache nearly useless.) 

If I were going to suggest an "ideal" solution, it would be this:
a. Move the cache logic into `eo_get_events()`
b. Build the cache key out of `$query_array` at https://github.com/stephenharris/Event-Organiser/blob/2.12.0/includes/event-organiser-event-functions.php#L128
c. Put a filter on the query args before they're passed to the filter, but after they're parsed with the defaults. Probably just after this line https://github.com/stephenharris/Event-Organiser/blob/2.12.0/includes/event-organiser-event-functions.php#L113

Advantages: you get query caching all the time, not just in AJAX requests; people can choose to unhook your AJAX handlers and provide their own without rebuilding cache support; cache keys are pretty much built from a whitelist (though not strictly, since you could add something like 'bp_group_id' to the `$query_array`) which means you don't have to deal with garbage in `$_REQUEST`. 

What do you think of this general approach? I could write up a PR if you thought it was something you'd consider. If not, we'll probably go forward with the `'pre_transient_'` filters.

**Comment by stephenharris** [comment]
You make a good point regarding (3). 

Unfortunately it's not possible to cache inside `eo_get_events()`, it accepts relative date strings for the arguments `event_start_after`, `event_end_before`, etc. (e.g. 'now', 'this monday' etc). Obviously these sort of queries just aren't cacheable. `eo_get_events()` is also part of the public API so there are potentially scripts out for which caching would break them (e.g. imagine globals being used at `pre_get_posts`).

It looks like (2) might be the way forward? I'll open a ticket on EO...

**Comment by stephenharris** [comment]
Just a thought - how are you using `$_GET['bp_group_id']` if you can't inject it into `$query`? I assume you're using `eventorganiser_fullcalendar_event`?

In general might make more sense to filter `$query` rather than the cache key (even if in this case you only alter `$query` to invalidate the cache).

**Comment by boonebgorges** [comment]
> Just a thought - how are you using $_GET['bp_group_id'] if you can't inject it into $query? I assume you're using eventorganiser_fullcalendar_event?

Maybe @christianwach can say more about this. It looks like we're fetching the entire calendar and then filtering out irrelevant events based on the group ID. This, of course, suggests that per-group caching should be irrelevant. But this way of filtering for group events is also not efficient, and I would like to switch to a different method that would involve passing a 'bp_group_id' param to `eo_get_events()`, which would then be handled like this https://github.com/cuny-academic-commons/bp-event-organiser/blob/master/includes/group.php#L125

And yes, filtering the `$query` would be fine.

**Comment by christianwach** [comment]
@stephenharris once again, thanks for your thoughts on this matter. @boonebgorges is essentially right about the filtering process. The group ID is injected into the AJAX request for the calendar and then irrelevant events are dumped by filtering `eventorganiser_fullcalendar_event`. It works, but it's far from ideal.

I like the idea of filtering the `$query` - presumably this will allow filtering and injection techniques similar those used in BuddyPress?

**Comment by stephenharris** [comment]
I'm not familar with BuddyPress' codebase, so I'm not sure what filtering/injection techniques you're referring to. But `$query` (which will be filtered) is passed to `eo_get_events()` which is little more than a wrapper for `get_posts()`. As such any key/values you add to add the query (array) will be be available at `pre_get_posts` action or `posts_request` filter. 

That'd be more efficient than using `eventorganiser_fullcalendar_event`.

**Comment by r-a-y** [comment]
Thanks for the feedback, @stephenharris.  This is what I would recommend:
1. Add a new filter to allow manipulation of the `$key` variable inside the `eventorganiser_public_fullcalendar()` function - https://github.com/stephenharris/Event-Organiser/blob/master/includes/event-organiser-ajax.php#L71.  This will allow us to set a unique key.  Something like:
   
    `$key = apply_filters( 'eo_transient_key', "eo_fc_".md5( serialize( $query ). $time_format ), $query, $time_format );`
2. Then, we'll also hook into the `pre_transient_$transient` / `pre_set_transient_$transient` filters to bail out of using EO's default transient.  I don't want to cache BP's calendars inside EO's transient.  Let's either add our own transient or use the WP cache API (`wp_cache_get()`).
3. Hook into `'pre_get_posts'` early to inject our `bp_group` parameter to the WP_Query since we already alter the post query here and will be able to query group events for free:
   https://github.com/cuny-academic-commons/bp-event-organiser/blob/master/includes/group.php#L125.  This is similar to Boone's comment [here](https://github.com/cuny-academic-commons/bp-event-organiser/issues/2#issuecomment-84362925).

**Comment by stephenharris** [comment]
Hi @r-a-y There's a filter for the actual `$query` array, from which `$key` is generated (at least in this latest revision https://github.com/stephenharris/Event-Organiser/pull/251). So you can bust the cache key by modifying that query. 

But if you're going to disable the cache via `pre_transient_$transient`, then whatever the `$key` is is irrelevant. 

Lastly, if you inject the `bp_group` parameter into `$query` it will be available at `pre_get_posts`. 

I guess my question is, if you can modify `$query` and the `$key` is uniquely determined by `$query`, what is the value in filtering it?

**Comment by r-a-y** [comment]
>  There's a filter for the actual $query array, from which $key is generated (at least in this latest revision stephenharris/Event-Organiser#251). So you can bust the cache key by modifying that query.

Ahh nice.  That should solve most of our problems.  Wasn't aware of your working branch!  I guess BP Event Organiser will require at least v2.13.0.

We can probably hook onto the `'eventorganiser_fullcalendar_query'` filter to inject the `'bp_group'` parameter and that should query group events.

I still want to bail out of EO's transient to avoid bloating it.  What do you think, @boonebgorges?

**Comment by boonebgorges** [comment]
> I still want to bail out of EO's transient to avoid bloating it. What do you think, @boonebgorges?

Certainly we would bloat it, as there may be hundreds of groups with calendars. We're also bound to run into race conditions storing it all in a single transient. A more scalable invalidation strategy is to use an incrementor, like WP's `'last_changed'`; use it when concatenating cache keys, and then invalidate all related cache values simply by incrementing `'last_changed'`.

I'm fine with bypassing EO's transients. Whether that means using our own transients, or WP's persistent cache API, I don't have a strong opinion.

**Comment by christianwach** [comment]
Do we also need to consider user calendars in addition to group calendars?

**Comment by boonebgorges** [comment]
Yes. :)

**Comment by r-a-y** [comment]
Or maybe we do not even consider caching for a first release.  We'll hijack the `'eventorganiser_fullcalendar_query'` filter so we can query only group events / user events and just bail out of transient saving.

**Comment by christianwach** [comment]
@r-a-y That's the way the plugin already works, though it explicitly busts the caches at present. Using the  `pre_transient_` and `pre_set_transient_` filters should avoid the need to do so.

**Comment by r-a-y** [comment]
> That's the way the plugin already works

Not really.  Doesn't EO query all events by default and then we remove events that are not part of the current group?  The [new filter by Stephen](https://github.com/stephenharris/Event-Organiser/commit/d01193c4b11934513bf48b9618b4da7632a88388) should allow us to specifically query our events during the initial fetch without us needing to parse each event afterwards.

Then, we can bail out of the transient fetching / saving.  Although bailing out will still require some check on `$_POST` during the `pre_transient` / `pre_set_transient` filters for our group parameter.

**Comment by christianwach** [comment]
@r-a-y Ah, yes sorry, I misread `eventorganiser_fullcalendar_query` as `eventorganiser_fullcalendar_event`.

**Comment by christianwach** [comment]
Having said that, if we're going to short-circuit EO's caching entirely, then [Stephen's code](https://github.com/stephenharris/Event-Organiser/pull/248#issuecomment-84051412) should do the trick without further checks, shouldn't it?

**Comment by r-a-y** [comment]
Yes and no.  We shouldn't disable the transient caching that EO offers by default for their own calendars.  At least, that's what I think.

**Comment by boonebgorges** [comment]
> We shouldn't disable the transient caching that EO offers by default for their own calendars. At least, that's what I think.

+1. Currently, if you visit a group calendar, it'll bust all calendar caches, even those not related to groups. At the very least, the 'pre_transient_' method will allow us to stop doing this.

**Comment by christianwach** [comment]
But won't the content of "global" calendars be subject to filtering depending on the person viewing them? As I understand it, events in groups that are not public and that the person is not a member of shouldn't show up in global calendars. So wouldn't we have to bust caches on a per-person basis anyway?

I'm not clear how this is this functionally different to busting caches on viewing a group's calendar, or for that matter, a person's "personal" calendar on their profile page. A group calendar only shows events in that group, whilst a personal calendar shows only events in public, private and hidden groups that the person a member of. 

In the light of this, it seems to me that there are no truly "global" calendars in a BuddyPress context - because a "global" calendar should show:
- Events unrelated to a group
- Events in public, private and hidden groups that I am a member of

As I understand it, EO's built-in cache does not handle the latter kind of event, so we'd either have to enhance it to do so or handle caching of global calendars ourselves. Which basically boils down to short-circuiting EO's cache anyway.

Sheesh, I can now see the truth in that quote "there are two hard things in computer science: cache invalidation, naming things, and off-by-one errors."

**Comment by boonebgorges** [comment]
@christianwach You are correct that calendars will essentially be per-user. It looks at a glance like EO doesn't really support this. There are private events, but it appears that they're only visible for users with the 'read_private_events' cap, so it's a simple toggle. (Thus EO's relatively simple `_priv` toggle for cache keys.) So, I guess, for logged-in users we will essentially always be sidestepping EO's built-in cache.

In the medium-term, let's think about what a per-user + per-group cache schema (and invalidation strategy) will look like. In the short term, let's just bypass the EO cache with the 'pre_transient' filters rather than deleting it as is currently the case.

**Comment by boonebgorges** [comment]
As we're bypassing the cache altogether, I'm going to close this ticket. In the future we might want to do our own caching, but let's cross that bridge when we come to it.
