### ISSUE TITLE
Single event: expose .ics file download

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#21]
I'm pretty sure event-organiser has built-in support for .ics subscription for single events. We should expose this somehow in our interface.

**Comment by r-a-y** [comment]
In an ideal world, we would piggyback on what EO uses (/feed/eo-events/), but due to post ID conflicts with BP, I'll probably have to manually spawn the iCal download.  Should be easy with EO's built-in functions.

Probably via `example.com/members/admin/events/MY-EVENT/feed/` or `example.com/members/admin/events/MY-EVENT/ical/`

**Comment by r-a-y** [comment]
My previous comment was invalid.

I'm piggybacking off of EO's default iCal link via the canonical event permalink with the `/feed/eo-events/` suffix.

Might need to do some work with permissions though.
