### ISSUE TITLE
Top-level CPT single view should match group/user context view

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#31]
Currently, they don't look alike at all. Is this totally theme dependent?

**Comment by r-a-y** [comment]
Are you talking about `example.com/events/event/POST-SLUG`?

This is handled by EO's default template.  I do not think we should do anything for EO's default template.

By that, I mean we shouldn't force the BP interface on it.  If we do want to do something, my thoughts are we should just widen the template and make it look less like a WP post.

Widening the template is something that we cannot do for all WP themes due to theme compatibility, but it's something we can do for CAC.

**Comment by boonebgorges** [comment]
Yeah, I do mean that kind of URL. I agree that we shouldn't force the BP 
interface on it, but it would be nice if the event-related content were 
formatted in a way that's reasonably similar to the way it appears in 
the group and user context. At least in bp-nelo, it's very different. 
Maybe use a common "event-content" template, and inject it as necessary? 
(I'm saying this without having looked at how this is handled natively 
by EO.)

**Comment by r-a-y** [comment]
I think I've done enough to address this for the plugin.

For CAC, we can copy `single.php` from bp-default, paste in our theme directory and rename to `single-event.php` to do additional mods there.

**Comment by r-a-y** [comment]
Going to close this one.
