### ISSUE TITLE
Upcoming Events archive

### ISSUE THREAD

**Issue by christianwach** [cuny-academic-commons/bp-event-organiser#32]
I've posted [a gist for an "upcoming events" archive](https://gist.github.com/christianwach/90d636ac51e0af43096b), as per Stephen's code hints (which I can't find right now) - I reckon a list view would be a useful addition. I've posted it separately as it's code I use outside of a BP context that I wanted to offer up for review, plus there'll most likely need to be some kind of check for naming collisions before inclusion.

Thoughts?

**Comment by christianwach** [comment]
I should mention that this is [implemented on IHC](http://islamichistorycommons.org/events/event/upcoming-events/), though there are no events at present. The IHC site has a custom 'archive-event.php' template (amongst others) for showing this.

**Comment by boonebgorges** [comment]
Thanks, Christian. This is related to #25. I'm not sure whether having a 
separate rewrite endpoint for this is necessary within the context of 
bp-event-organiser (as you note), especially since we would want this to 
work within group/user contexts as well. But let's definitely look at 
what you've written here as we think more about #25

**Comment by christianwach** [comment]
@boonebgorges Thanks - I'd overlooked that issue.

**Comment by boonebgorges** [comment]
As part of #25, I decided to go with the suggestion of calling this list "Upcoming" - it didn't seem obviously useful to me to have a list view of past events. I did implement it slightly differently from what you suggested here. See the commits attached to #25 for more details.
