### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by christianwach** [cuny-academic-commons/bp-event-organiser#43]
I haven't had a chance to investigate this yet, but thought I'd flag [Event Organiser FES 1.2: Frontend Editing](http://wp-event-organiser.com/blog/announcements/event-organiser-fes-1-2-frontend-editing/) which may make some of the front-end editing in this plugin superfluous.

**Comment by r-a-y** [comment]
We were aware of FES before building out what is currently in the repo.

[Event Organiser FES](http://wp-event-organiser.com/extensions/event-organiser-frontend-submissions/) is a paid developer extension, which I haven't had a chance to take a look at due to the availability.

Instead, [what I built](https://github.com/cuny-academic-commons/bp-event-organiser/tree/master/includes/wp-frontend-admin-screen) is the ability for the WP admin edit post backend to be usable on the frontend.  This gives us more flexibility with existing WP code (eg. metaboxes).

Stephen's FES is probably better for non-BuddyPress installations, since the frontend stuff in BP Event Organiser is all tied to BP permalinks.

**Comment by christianwach** [comment]
Thanks for the feedback @r-a-y
